input {
  kafka {
    bootstrap_servers => "kafka:19092"
    topics => ["logs"]
    group_id => "logstash-consumer-group"
    codec => json
    auto_offset_reset => "earliest"
    consumer_threads => 1
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "kafka-logs-%{+YYYY.MM.dd}"
  }
  
  # For debugging
  stdout { 
    codec => rubydebug 
  }
}
